name: Build & Test Backend for Development, Publish PreRelease Version

on:
  push:
    branches:
      - dev
    paths:
      - 'src/**'

env:
  DOTNET_VERSION: '8.0'
  SOLUTION_PATH: 'src/Deployment.Automation.Learning.sln'
  TESTS_SOLUTION_PATH: 'test/Deployment.Automation.Learning.Tests.sln'
  PACKAGES_PATH: 'src'

jobs:
  build_and_test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

  publish_prerelease:
    needs: build_and_test
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Packable Projects
        run: |
          # Find all csproj files and check for PackageId, ensuring xargs exits successfully
          echo "Finding projects with PackageId defined..."
          PACKABLE_PROJECTS=$(find ${{ env.PACKAGES_PATH }} -name '*.csproj' -print0 | xargs -0 -I {} bash -c "grep -q '<PackageId>' {} && echo {} || true")
          echo "PACKABLE_PROJECTS<<EOF" >> $GITHUB_ENV
          echo "$PACKABLE_PROJECTS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Display packable projects
        run: |
          echo "Packable projects found:"
          echo "$PACKABLE_PROJECTS"

      - name: Pack and Push Each Project
        run: |
          for CS_PROJ in $(echo "$PACKABLE_PROJECTS")
          do
            # Correctly extract the major version from DOTNET_VERSION
            DOTNET_MAJOR_VERSION=$(echo "${{ env.DOTNET_VERSION }}" | cut -d '.' -f1)  
          
            # Extract Package ID
            PACKAGE_ID=$(grep '<PackageId>' "$CS_PROJ" | sed -n 's/.*<PackageId>\(.*\)<\/PackageId>.*/\1/p')
            if [ -z "$PACKAGE_ID" ]; then
              echo "Skipping project $CS_PROJ, because PackageId not specified"
              continue
            fi

            # Extract Version
            VERSION=$(grep '<Version>' "$CS_PROJ" | sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p')
            if [ -z "$VERSION" ]; then
              echo "Error: Skipped package $CS_PROJ, because Version is not specified"
              continue
            fi

            echo "Current version of package $CS_PROJ is $VERSION"

            # Extract the major, minor, patch and alpha numbers
            MAJOR=$(echo $VERSION | cut -d '.' -f1)
            MINOR=$(echo $VERSION | cut -d '.' -f2)
            PATCH=$(echo $VERSION | cut -d '.' -f3 | grep -o '^[0-9]*')
            ALPHA_SUFFIX=$(echo $VERSION | grep -o '[a-zA-Z]*')
            ALPHA_NUMBER=$(echo $VERSION | grep -o '[0-9]*$')

            # Check if the alpha suffix and alpha number exist
            if [[ -z "$ALPHA_SUFFIX" || -z "$ALPHA_NUMBER" ]]; then
              echo "Error: Skipped package $CS_PROJ, because Version does not have an alpha suffix and alpha number"
              continue  
            fi

            # Fetch latest version from NuGet
            echo "Fetching latest version for package $PACKAGE_ID from NuGet..."
            LATEST_VERSION=$(nuget list $PACKAGE_ID -PreRelease | grep "$PACKAGE_ID" | awk '{print $2}')
            echo "Latest version fetched: $LATEST_VERSION"

            if [[ "$MAJOR" != "$DOTNET_MAJOR_VERSION" ]]; then
              echo "Error: Skipped package $CS_PROJ, because of major version mismatch. Expected major version: $DOTNET_MAJOR_VERSION, but found $MAJOR"
              continue
            fi

            if [[ ! -z "$LATEST_VERSION" && $LATEST_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.[0-9]+)?)?$ ]]; then

              # Extract major, minor, and patch version from latest version
              LATEST_MAJOR=$(echo $LATEST_VERSION | cut -d '.' -f1)
              LATEST_MINOR=$(echo $LATEST_VERSION | cut -d '.' -f2)
              LATEST_PATCH=$(echo $LATEST_VERSION | cut -d '.' -f3 | grep -o '^[0-9]*')

              # Validate current version against the latest version
              if echo $LATEST_VERSION | grep -q 'alpha'; then

                LATEST_ALPHA_NUMBER=$(echo $LATEST_VERSION | grep -oP 'alpha.\K\d+')
                  if [[ $ALPHA_NUMBER -ne $((LATEST_ALPHA_NUMBER + 1)) ]]; then
                    echo "Error: Skipped package $CS_PROJ, because current alpha number is not one above the latest alpha number"
                    continue
                  fi
              else

                if [[ $MINOR -ne $((LATEST_MINOR + 1)) && $PATCH -ne $((LATEST_PATCH + 1)) ]]; then
                  echo "Error: Skipped package $CS_PROJ, because either the minor or patch version is not one higher than the latest version"
                  continue
                fi

              fi
            fi

            # Pack the project with the new version
            echo "Packing project $CS_PROJ with version $VERSION"
            dotnet pack $CS_PROJ -c Release -o ./nupkgs /p:PackageVersion=$VERSION
    
            # Push the package to NuGet
            echo "Pushing package ${PACKAGE_ID}.${VERSION}.nupkg"
            dotnet nuget push "./nupkgs/${PACKAGE_ID}.${VERSION}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --no-service-endpoint
          done