name: Build and Test pushed changes for backend on dev branch

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0'
  SOLUTION_PATH: 'src/Deployment.Automation.Learning.sln'

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

    - name: Run tests (optional)
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-restore --verbosity normal

    - name: Publish (optional)
      run: dotnet publish ${{ env.SOLUTION_PATH }} -c Release -o out --no-restore
