name: Build & Test Backend for Development, Publish PreRelease Version

on:
  push:
    branches:
      - dev

env:
  DOTNET_VERSION: '8.0'
  SOLUTION_PATH: 'src/Deployment.Automation.Learning.sln'
  PACKAGES_PATH: 'src'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

  publish_prerelease:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Packable Projects
        run: |
          echo "Finding projects with PackageId defined..."
          PACKABLE_PROJECTS=$(find ${{ env.PACKAGES_PATH }} -name '*.csproj' | xargs -I {} sh -c "grep -q '<PackageId>' {} && echo {}")
          echo "PACKABLE_PROJECTS<<EOF" >> $GITHUB_ENV
          echo "$PACKABLE_PROJECTS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Display packable projects
        run: |
          echo "Packable projects found:"
          echo "$PACKABLE_PROJECTS"

      - name: Pack and Push Each Project
        run: |
          for CS_PROJ in $(echo "$PACKABLE_PROJECTS")
          do
            # Get package ID
            PACKAGE_ID=$(grep '<PackageId>' $CS_PROJ | sed -n 's/.*<PackageId>\(.*\)<\/PackageId>.*/\1/p')

            # Fetch the latest pre-release version from NuGet
            echo "Getting latest pre-release version for $PACKAGE_ID..."
            LATEST_VERSION=$(aarnaud/nugetversion@v1.0.4 --id $PACKAGE_ID --project-path $CS_PROJ --prerelease)
            echo "Latest pre-release version fetched: $LATEST_VERSION"

            # Pack nuget package
            PACKAGE_VERSION="$LATEST_VERSION-alpha.$(($(echo $LATEST_VERSION | grep -oP 'alpha.\d+' | grep -oP '\d+') + 1))"
            echo "New version will be $PACKAGE_VERSION"
            dotnet pack $CS_PROJ -c Release -o ./nupkgs /p:PackageVersion=$PACKAGE_VERSION

            # Pushing package to Nuget source
            dotnet nuget push "./nupkgs/${PACKAGE_ID}.${PACKAGE_VERSION}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --no-service-endpoint
          done